### ISSUE TITLE
https://github.com/JeffMuniz/Jenkins/tree/main/ScriptsLocalGitHub/tecnologies/Sec/Firewall_Clientes

### ISSUE THREAD

**Issue by smancini42** [JeffMuniz/Jenkins#1]
Por favor, remova os arquivos da ACSC, pois estão todos listados nesse repositório.

https://github.com/JeffMuniz/Jenkins/tree/main/ScriptsLocalGitHub/tecnologies/Sec/Firewall_Clientes

Atenciosamente.

Sidinei Mancini Junior
Rede Santa Catarina
sidinei.mancini@redesc.org.br

**Comment by JeffMuniz** [comment]
Perdão mestre, commit no repositório errado, obrigado por avisar!

**Comment by smancini42** [comment]
Chefe ainda esta lá!!!

Tira do seu branch pq senao ele sobe o arquivo todas as vezes que voce upar algo.

Atenciosamente.

Sidinei Mancini Junior
Rede Santa Catarina
sidinei.mancini@redesc.org.br
